openapi: 3.0.0
info:
  title: eformsign
  version: '2.0'
  contact:
    name: eformsign Service Team
    email: eformsign@forcs.com
    url: www.eformsign.com
  description: eformsign이 제공하는 API를 통해 eformsign의 기능을 고객의 시스템/서비스에서 호출해 사용할 수 있습니다.
  termsOfService: 'https://www.eformsign.com/eform/account/terms.html?tab=0'
servers:
  - url: 'https://api.eformsign.com/v2.0'
paths:
  /api_auth/access_token:
    post:
      operationId: post-api_auth-access_token
      description: API 키로 Access Token을 발급받습니다.
      parameters:
        - schema:
            type: string
          in: header
          name: Content-Type
          description: application/json
          required: true
        - schema:
            type: string
          in: header
          name: eformsign_signature
          description: execution_time 값을 private Key로 서명한 값
          required: true
        - schema:
            type: string
          in: header
          name: Authorization
          description: Bearer <api key>
      summary: Access Token 발급
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: ''
              properties:
                execution_time:
                  type: integer
                  format: int64
                  description: 'API 호출 시간(현재 시간)으로, 서버시간의 +/- 30초 내에서만 호출이 유효하다.'
                member_id:
                  type: string
                  description: '회사 멤버의 ID로, 회사 멤버의 Access token을 발급받을 때 추가로 입력한다.'
              required:
                - execution_time
            examples:
              Request:
                value:
                  execution_time: 1533011071001
          application/xml:
            schema:
              type: object
              properties: {}
        description: ''
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json
          content:
            application/json:
              schema:
                type: object
                properties:
                  api_key:
                    type: object
                    description: 'API Key 정보로, name, alias, company등의 객체를 포함한다.'
                    properties:
                      name:
                        type: string
                        description: API Key 이름
                      alias:
                        type: string
                        description: API Key 별칭
                      company:
                        type: object
                        description: 'API Key의 회사 정보로, id, name, api_url 객체를 포함한다.'
                        properties:
                          id:
                            type: string
                            description: 회사 ID
                          name:
                            type: string
                            description: 회사명
                          api_url:
                            type: string
                            description: 회사의 서비스 API URL
                  oauth_token:
                    type: object
                    description: '토큰 정보로, token_type, access_token, refresh_token, expires_in 객체를 포함한다.'
                    properties:
                      token_type:
                        type: string
                        description: 토큰 타입(JWT 고정)
                      access_token:
                        type: string
                        description: access token
                      refresh_token:
                        type: string
                        description: refresh token
                      expires_in:
                        type: integer
                        description: 'Access token 유효시간(초)으로, Access token 발급 시점부터 expires_in 시간까지만 유효하다.'
              examples:
                Response Success:
                  value:
                    api_key:
                      name: access key
                      alias: access Key alias
                      company:
                        company_id: 129jd93j29jd9j29jd
                        name: Forcs
                        api_url: 'https://kr-api.eformsign.com'
                    oauth_token:
                      token_type: JWT
                      access_token: eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJvY2UuaWFtIiwiY29udGV4dCI6eyJjbGllbnRJZCI6IjE5MzEyYWI2NWQxMT...
                      refresh_token: dcaf137b-e93e-4207-ba8a-2dd5a1250c45
                      expires_in: 3600
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: 에러 코드
                  ErrorMessage:
                    type: string
                    description: 에러 메시지
                  execution_time:
                    type: integer
                    format: int64
                    description: 수행 시간
              examples:
                Response Failed 1:
                  value:
                    code: '4000002'
                    ErrorMessage: The validation time has expired.
                    execution_time: 1600247345051
                Response Failed 2:
                  value:
                    code: '4030001'
                    ErrorMessage: invalid api key
      tags:
        - eformsign
    parameters: []
tags:
  - name: eformsign
